"""This contains a list of table columns to use for each table in the data set."""
table_keys = {
    "BO-aftale-haendelse": ["Ekstern_reference_nøgle"],
    "BO-aftale": ["Aftalenummer", "Bilagsnummer", "Position"],
    "Bilag-aaben": None,
    "Bilag-lukket": ["Dato-ID", "Identifikation", "Intervalnummer", "Recordnummer"],
    "Bilag-master": ["Bilagsnummer", "Gentagelsesposition", "Position", "Delposition"],
    "FP-aftale": None,
    "Forretningspartner": ["Klient", "Forretningspartner", "Identifikationsart", "Identifikationsnr.", "Forretningspartner-GUID"],
    "Indbetalinger": ["Art_kilde", "Betalingsidentifikator", "Løbenummer"],
    "Opsaetning-Aftalekontotype": ["Klient", "Sprognøgle", "Aftalekontotype"],
    "Opsaetning-Rykkerniveau": ["Sprognøgle", "Rykkeprocedure", "Rykkeniveau"],
    "RIM-aftale-rater": None,
    "RIM-aftale-renter": ["Aftalenummer", "Intr-posnr"],
    "RIM-aftale": None,
    "Rykker": ["Dato-ID", "Identifikation", "Forretningspartner", "Aftalekonto", "Rykkertæller", "Bilagsnummer", "Gentagelsesposition", "Position", "Delposition"],
    "UU-aftale-haefter": ["Klient", "Aftalenummer", "Forretningspartner"],
    "UU-aftale": None,
}

table_date_columns = {
    "BO-aftale-haendelse": ["Afskrivnings_dato", "Betalingsdato"],
    "BO-aftale": None,
    "Bilag-aaben": "Bogføringsdato",
    "Bilag-lukket": "Bogføringsdato",
    "Bilag-master": "Registreringsdato",
    "FP-aftale": "Oprettet_den",
    "Forretningspartner": None,
    "Indbetalinger": "Oprettet_den",
    "Opsaetning-Aftalekontotype": None,
    "Opsaetning-Rykkerniveau": None,
    "RIM-aftale-rater": "Oprettet_den",
    "RIM-aftale-renter": "Oprettet_den",
    "RIM-aftale": "Oprettet_den",
    "Rykker": "Udstedelsesdato",
    "UU-aftale-haefter": None,
    "UU-aftale": None,
}

table_used_columns = {
    "BO-aftale-haendelse": ["Afskrevet",
                            "Afskrivnings_dato",
                            "Aftalenummer",
                            "Beløb",
                            "Betalingsdato",
                            "Bobehandling",
                            "Ekstern_reference_nøgle",
                            "Indbetalt_af_bobestyrer",
                            "Klient",
                            "Kommune_kode",
                            "Korrespondanceart",
                            "Printdato",
                            "Udtrækstype",
                            "Valuta",],
    "BO-aftale":           ["Ændringer_efter_første_anmeld",
                            "Afskrevet",
                            "Aftale",
                            "Aftalekonto",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Bilagsnummer",
                            "Bobehandling",
                            "Deltransaktion",
                            "Fjernet",
                            "Første_anmeldelse",
                            "Hovedtransaktion",
                            "Indbetalt_af_bobestyrer",
                            "Indholdsart",
                            "Kommune_kode",
                            "Oprettet_beløb",
                            "Position",
                            "Restbeløb",
                            "Valuta",],
    "Bilag-aaben":         ["Aftaleindhold",
                            "Aftalekonto",
                            "Aftalekontotype",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Antal_poster",
                            "Beløb",
                            "Beløb_intern_valuta",
                            "BevillAnsvarssted",
                            "Bevillingsposition",
                            "Bevillingsprogram",
                            "Bilagsdato",
                            "Bilagsnummer",
                            "Bogføringsdato",
                            "Dato-ID",
                            "Deltransaktion",
                            "Firmakode",
                            "Forretningspartner",
                            "Funktionsområde",
                            "Henstand_til",
                            "Hovedtransaktion",
                            "Identifikation",
                            "Indholdsart",
                            "Kapitalmidler",
                            "Klient",
                            "Kommune_kode",
                            "Kredit_oprindelses_dato",
                            "Landenøgle",
                            "Nettoforfald",
                            "Original-FI-område",
                            "Periodenøgle",
                            "Position",
                            "Positionstekst",
                            "Postnummer",
                            "Referencebilagsnr.",
                            "Registreringsdato",
                            "Rykkeniveau",
                            "Rykkeniveautype",
                            "Rykkeprocedure",
                            "Rykkeproceduretype",
                            "SBS_dokumentnummer",
                            "Skæringsdato",
                            "Sorteringsbetegnelse",
                            "Statistiknøgle",
                            "Udligning_kredit_oprindelse",
                            "Udligningsstatus",
                            "Valuta"],
    "Bilag-lukket":        ["Afskrivningsårsag",
                            "Afskrivningsdato",
                            "Aftaleindhold",
                            "Aftalekonto",
                            "Aftalekontotype",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Antal_poster",
                            "Bankafregningskonto",
                            "Beløb",
                            "Beløb_intern_valuta",
                            "BevillAnsvarssted",
                            "Bevillingsposition",
                            "Bevillingsprogram",
                            "Bilagsdato",
                            "Bilagsnummer",
                            "Bilagstype_markering",
                            "BogfDato_udligning",
                            "Bogføringsdato",
                            "Bortposteringsårsag",
                            "Dato-ID",
                            "Deltransaktion",
                            "Firmakode",
                            "Forretningspartner",
                            "Fra",
                            "Funktionsområde",
                            "Henstand_til",
                            "Hovedtransaktion",
                            "Identifikation",
                            "Indbetalingstype",
                            "Indholdsart",
                            "Kapitalmidler",
                            "Klient",
                            "Kommune_kode",
                            "Kredit_oprindelses_dato",
                            "Landenøgle",
                            "Nettoforfald",
                            "Original-FI-område",
                            "Position",
                            "Postnummer",
                            "Referencebilagsnr.",
                            "Registreringsdato",
                            "Rykkeniveau",
                            "Rykkeprocedure",
                            "SBS_dokumentnummer",
                            "Sorteringsbetegnelse",
                            "Statistiknøgle",
                            "Til",
                            "Tilbageført_via",
                            "Udligning",
                            "Udligning_kredit_oprindelse",
                            "Udligningsårsag",
                            "Udligningsbeløb",
                            "Udligningsbilag",
                            "Udligningsdato",
                            "Udligningsstatus",
                            "Udligningsvaluta",
                            "Underapplikation",
                            "Valørdato_udligning",
                            "Valuta"],
    "Bilag-master":        ["AfregnPeriode_fra",
                            "AfregnPeriode_til",
                            "Afskrivningsårsag",
                            "Aftale",
                            "Aftalekonto",
                            "Aftalekontotype",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Applikationsområde",
                            "Artskonto",
                            "Beløb",
                            "Beløb_intern_valuta",
                            "Betalingsordre",
                            "Bilagsart",
                            "Bilagsdato",
                            "Bilagsnummer",
                            "Bilagstype_markering",
                            "BogfDato_udligning",
                            "Bogføringsdato",
                            "Bortposteringsårsag",
                            "Delposition",
                            "Deltransaktion",
                            "Firmakode",
                            "Forretningspartner",
                            "Henstand_til",
                            "Hovedtransaktion",
                            "Indholdsart",
                            "Kommune_kode",
                            "KontofastsætKendet.",
                            "Momsindikator",
                            "Nettoforfald",
                            "Oprindelse",
                            "Position",
                            "Referencebilagsnr.",
                            "Referencenøgle",
                            "Referenceoperation",
                            "Registreringsdato",
                            "Rentenøgle",
                            "Rykkeprocedure",
                            "SBS_dokumentnummer",
                            "Skæringsdato",
                            "Statistiknøgle",
                            "Tilbageført_via",
                            "Udligngningstype",
                            "Udligningsårsag",
                            "Udligningsbeløb",
                            "Udligningsbilag",
                            "Udligningsdato",
                            "Udligningsstatus",
                            "Udligningsvaluta",
                            "Valørdato_udligning",
                            "Valuta",],
    "FP-aftale":           ["AA_type",
                            "Ændret_den",
                            "Aftale",
                            "Aftalekonto",
                            "Aftalenummer",
                            "Aftaleposition",
                            "Aftalestatus",
                            "Aftaletype",
                            "Årsag_til_luk_aftale",
                            "Besvaret",
                            "Bilagsnummer",
                            "Forretningspartner",
                            "Kommune_kode",
                            "Konvertering",
                            "Lukket_den",
                            "Niveau_Aftale_Position",
                            "Oprettet_den",
                            "Position",
                            "System_dato",
                            "Tilføjelsesdato",
                            "UdlBeløb_int._valuta",
                            "Valuta",],
    "Forretningspartner":  ["BW_Opdateringsmode",
                            "Datafordeleren_UUID",
                            "Forretningspartner",
                            "Forretningspartner-GUID",
                            "Gyldig_fra",
                            "Gyldig_til",
                            "Identifikationsart",
                            "Identifikationsnr.",
                            "Klient",
                            "Slettet",],
    "Indbetalinger":       ["Afdeling",
                            "Afklaringsstatus",
                            "Aftale",
                            "Aftalekonto",
                            "Annuller_status",
                            "Art_kilde",
                            "Bankafregningskonto",
                            "Bankforbindelse",
                            "Beløb",
                            "Betalings_art",
                            "Betalingsidentifikator",
                            "Betalingsmåde",
                            "Betalingsretning",
                            "Bilagsart",
                            "Bilagstype",
                            "Firmakode",
                            "Forretningsområde",
                            "Forretningspartner",
                            "Kasse",
                            "Kommune_kode",
                            "Konto-ID",
                            "Langtekst",
                            "Løbenummer",
                            "Oprettet_den",
                            "Skæringsdato",
                            "Tidsstempel_for_deltaekstrakt.",
                            "Underapplikation",
                            "Valørdato",
                            "Valuta",
                            "Varighed_af_afklaring",],
    "Opsaetning-Aftalekontotype":  ["Aftalekontotype",
                                    "Klient",
                                    "Kontotype_tekst",
                                    "Sprognøgle",],
    "Opsaetning-Rykkerniveau": ["Betegnelse",
                                "Kommune_kode",
                                "Rykkeniveau",
                                "Rykkeprocedure",
                                "Sprognøgle",],
    "RIM-aftale-rater":    ["Ændret_den",
                            "Aftale",
                            "Aftale_saldo",
                            "Aftalekonto",
                            "Aftalekontotype",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Basisdato_renteberegning",
                            "Bilagsnummer",
                            "Creation_Amount",
                            "Deltransaktion",
                            "EFI-nummer",
                            "Forældelsesdato",
                            "Fordringstype",
                            "Forretningspartner",
                            "Gentagelsesposition",
                            "Henstand_til",
                            "Hovedtransaktion",
                            "Indholdsart",
                            "Kommune_kode",
                            "Konvertering_status",
                            "KravsType",
                            "Markering_for_tilbagekald",
                            "Nettoforfald",
                            "Oprettet_den",
                            "Original_Amount",
                            "Position",
                            "Produktionsenh.",
                            "Ratespecifikation",
                            "ReturAarsagKode",
                            "ReturÅrsagText",
                            "Returdato",
                            "SBS_Document_Number",
                            "SBS_dokumentnummer",
                            "Sidste_rentefrie_indbetalingsdato",
                            "Slettes",
                            "Slutdato_for_forrentn.",
                            "SRI_dato",
                            "Status",
                            "Stiftelsesdato",
                            "System",
                            "System_dato",
                            "Text_Position_Number",
                            "Tilb._Virkningsdato",
                            "TilbageAarsagKode",
                            "UdlBeløb_int._valuta",
                            "Udligningsdato",
                            "Valørdato",
                            "Valuta",
                            "Ydelsesperiode_fra",
                            "Ydelsesperiode_til",],
    "RIM-aftale-renter":   ["Ændret_den",
                            "Afklarings_status",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Basisdato_renteberegning",
                            "EFI-nummer",
                            "Egen_reference",
                            "Forældelsesdato",
                            "Fordring_artskode",
                            "Fordring_kategorikode",
                            "Forretningspartner",
                            "Historisk_modtagelsesdato",
                            "Hovedfordring_id",
                            "Intr-posnr",
                            "Kommune_kode",
                            "Konvertering_status",
                            "KravsType",
                            "Markering_for_tilbagekald",
                            "Min._beløb_ignoreret",
                            "Modtagelsesdato",
                            "Oprettet_den",
                            "Oprettet_kl.",
                            "Overtagelse_af_inddrivelsesrenter",
                            "Periodetype_beskrivelse",
                            "P-nummer",
                            "Produktionsenh.",
                            "Rente,_år_til_dato_beløb",
                            "Rente,_år_til_dato_beløb,_DKK",
                            "Rentebeløb",
                            "Rentebeløb,_DKK",
                            "Renteperiode_slut-dato",
                            "Renteperiode_start-dato",
                            "ReturAarsagKode",
                            "ReturÅrsagText",
                            "Returdato",
                            "Slutdato_for_forrentn.",
                            "System_dato",
                            "Tilb._Virkningsdato",
                            "TilbageAarsagKode",
                            "Tjek_af_nr._I_Basissystem",
                            "Typekode",
                            "Udledt_fra_betaling",
                            "Udligningsdato",
                            "Underretnings-id",
                            "Valuta",
                            "Valutakode",],
    "RIM-aftale":          ["Åbent_beløb_for_perioden",
                            "ActionStatusCode",
                            "Ændret_den",
                            "Ændringsårsagskode",
                            "Ændringsårsagstekst",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Afvis",
                            "Aktionkode",
                            "Aktions-id",
                            "Basisdato_renteberegning",
                            "Beløb",
                            "Beløb_accepteret",
                            "Bilagsnummer",
                            "EFI-nummer",
                            "Forældelsesdato",
                            "Forretningspartner",
                            "Kommune_kode",
                            "KravsType",
                            "Krydsende_handling",
                            "Markering_for_tilbagekald",
                            "Medhæfter_status",
                            "Modtagelsesdato",
                            "Oprettet_den",
                            "Oprettet_kl.",
                            "Recall_Amount",
                            "Reduceret_beløb",
                            "Reference_til_ændring",
                            "Rest_beløb_markering",
                            "RestBeløb",
                            "ReturAarsagKode",
                            "ReturÅrsagText",
                            "Returdato",
                            "RIM_ændringsdato",
                            "SBS_dokumentnummer",
                            "Slutdato_for_forrentn.",
                            "Snitflade_Status",
                            "Status",
                            "System_dato",
                            "Tilb._Virkningsdato",
                            "TilbageAarsagKode",
                            "Trans_Beløb",
                            "Trans_flag",
                            "Trans_header_ID",
                            "Trans_sekvens_nr.",
                            "Transaktion_identifikator",
                            "Transdato",
                            "Transtid",
                            "UdlBeløb_int._valuta",
                            "Udligningsdato",
                            "UUID",
                            "Valuta",
                            "Valutanøgle",
                            "Virkningsdato",],
    "Rykker":              ["Aftale",
                            "Aftalekonto",
                            "Aftalekonto_ikke_entydig",
                            "Bilagsnummer",
                            "Dato-ID",
                            "Delposition",
                            "Firmakode",
                            "Forretningspartner",
                            "Gentagelsesposition",
                            "Identifikation",
                            "Kommune_kode",
                            "Nettoforfald",
                            "Nyt_rykkeniveau",
                            "Position",
                            "Printdato",
                            "Rentebilag",
                            "Rykkebeløb",
                            "Rykkeniveau",
                            "Rykkeniveautype",
                            "Rykkeprocedure",
                            "Rykker_annulleret",
                            "Rykkerenter",
                            "Rykkertæller",
                            "Rykkespærreårsag",
                            "Segment",
                            "Skæringsdato",
                            "Statistiknøgle",
                            "Suspenderings-rykkeniv.",
                            "Udskrevet",
                            "Udstedelsesdato",
                            "Valuta",],
    "UU-aftale-haefter":   ["Aftale",
                            "Aftalekonto",
                            "Aftalenummer",
                            "BetFormReference",
                            "Forretningspartner",
                            "Hæfter_fjernet",
                            "Hæfter_tilføjet",
                            "Hovedhæfter",
                            "Klient",
                            "Kommune_kode",],
    "UU-aftale":           ["Aftale",
                            "Aftalekonto",
                            "Aftalenummer",
                            "Aftalestatus",
                            "Aftaletype",
                            "Beløb",
                            "Bilagsnummer",
                            "Deltransaktion",
                            "Hovedtransaktion",
                            "Indholdsart",
                            "Kommune_kode",
                            "Position",
                            "Udligningsstatus",
                            "Valuta",],
}